

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Jean Dujardin",
    "number": "+41778977898"
}


###
GET http://localhost:3001/api/persons/

### 
GET http://localhost:3001/api/persons/69b295dcaabc42aebdda2ae4

###
DELETE http://localhost:3001/api/persons/69b2d0cedba1362b318469c9

###
PUT http://localhost:3001/api/persons/69b295dcaabc42aebdda2ae4 HTTP/1.1
Content-Type: application/json

  {
    "name": "Jean Dujardin",
    "number": "+33778977898",
    "id": "69b295dcaabc42aebdda2ae4"
  }



###
POST http://phonebook-4a84.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Jean Dujardin",
    "number": "+41778977898"
}

###
GET http://phonebook-4a84.onrender.com/api/persons/

###
DELETE http://phonebook-4a84.onrender.com/api/persons/8