###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "jcheval",
    "name": "Julien Chevalley",
    "password": "yourPassword"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "sekret"
}



###
GET http://localhost:3001/api/users/
